name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BiwengerApp
          path: bin/*.apk
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y \
            libsqlite3-dev zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev \
            libffi-dev libssl-dev libjpeg-dev libfreetype6-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libglu1-mesa libgles2-mesa-dev libmtdev-dev xclip xsel \
            libgstreamer1.0 libgstreamer1.0-dev gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav \
            libusb-dev libusb-1.0-0-dev libudev-dev \
            openjdk-11-jdk unzip zip

      - name: Build APK
        run: |
          pip install buildozer
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: biwenger-apk
          path: bin/*.apk
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y \
            libsqlite3-dev zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev \
            libffi-dev libssl-dev libjpeg-dev libfreetype6-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libglu1-mesa libgles2-mesa-dev libmtdev-dev xclip xsel \
            libgstreamer1.0 libgstreamer1.0-dev gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav \
            libusb-dev libusb-1.0-0-dev libudev-dev \
            openjdk-11-jdk unzip zip

      - name: Build APK
        run: |
          pip install buildozer
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: biwenger-apk
          path: bin/*.apk
